### ISSUE TITLE
sfdmu github actions possibly out of date

### ISSUE THREAD

**Issue by readeral** [hardisgroupcom/sfdx-hardis#668]
I'm wondering if the github workflows files are out of date?

In particular I've noticed that the file process-deploy.yml currently has installing sfdmu commented out, where other files like azure and the docker image don't.

The github file also specifies Node v18 where I noted sfdx-hardis was bumped to v20 3 weeks ago.

Is it safe for me to update both these items in my local project?

**Comment by nvuillam** [comment]
@readeral sfdmu is commented to gain some seconds, because configuration data deployments is not used often (in that case, it must be uncommented)

Docker image is unique (and not compatible with GitHub & Azure because based on docker alpine ), so it contains all plugins that can be used, the few megas of difference do not impact negatively the loading time (on Gitlab for example)

All workflows not using docker should use Node20, thanks for reporting, I'll fix that ASAP :)

Meanwhile, it's totally safe to fix the workflow directly in your project

**Comment by nvuillam** [comment]
> The github file also specifies Node v18 where I noted sfdx-hardis was bumped to v20 3 weeks ago.

@readeral  Solved in latest version :)

**Comment by readeral** [comment]
Ok cool, so I had understood that sfdmu is broken with salesforce cli ("does not play well" is subjective!), but actually it's commented out for being slow. But it can still be used ok.

Thanks for the clarification and bumping node version!

**Comment by readeral** [comment]
Also I love the login url example solution! Great work

**Comment by nvuillam** [comment]
@readeral at that time it was crashing on github, it's probably not the case anymore but let's uncomment it only when we really need it :)

**Comment by nvuillam** [comment]
(i"ll change the comment ^^)
